%%{init: {'flowchart': {'htmlLabels': true, 'nodeSpacing': 32, 'rankSpacing': 64, 'curve': 'linear'}} }%%
flowchart TB
    %% DFD notation: E# external entity, #.0 process, D# data store
    subgraph dfd_public["Internet / Client Boundary"]
        direction LR
        react(("1.0 React"))
    end
    style dfd_public fill:#ffffff,stroke:#404040,stroke-width:2px,stroke-dasharray: 7 4
    subgraph dfd_application["Application Trust Boundary"]
        direction LR
        node_js(("2.0 Node.js Backend"))
    end
    style dfd_application fill:#ffffff,stroke:#404040,stroke-width:2px,stroke-dasharray: 7 4
    subgraph dfd_data["Data Trust Boundary"]
        direction LR
        mongodb[("D1 Mongodb")]
    end
    style dfd_data fill:#ffffff,stroke:#404040,stroke-width:2px,stroke-dasharray: 7 4
    subgraph dfd_third_party["Third-Party Trust Boundary"]
        direction LR
        cognito["E1 Cognito"]
    end
    style dfd_third_party fill:#ffffff,stroke:#404040,stroke-width:2px,stroke-dasharray: 7 4
    node_js ==>|TCP| mongodb
    node_js ==>|HTTPS| cognito
    react ==>|HTTPS| node_js
    classDef dfdEntity fill:#ffffff,stroke:#202020,stroke-width:2px,color:#111111
    classDef dfdProcess fill:#ffffff,stroke:#202020,stroke-width:2px,color:#111111
    classDef dfdStore fill:#ffffff,stroke:#202020,stroke-width:2px,color:#111111
    class node_js dfdProcess
    class mongodb dfdStore
    class cognito dfdEntity
    class react dfdProcess