from datetime import datetime
from typing import List
from ..models import AnalysisResult, Threat, SystemArchitecture

class ReportGenerator:
    @staticmethod
    def generate_markdown(result: AnalysisResult) -> str:
        """
        Generates a two-tier markdown report: Confirmed Risks & Potential Risks.
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Separate threats by tier
        confirmed = [t for t in result.threats if t.tier == "Confirmed"]
        potential = [t for t in result.threats if t.tier == "Potential"]
        
        md = []
        md.append(f"# Threat Model Report: {result.project_name}")
        md.append(f"**Date:** {now}")
        md.append(f"**Security Score:** {result.score}/100")
        md.append(f"**Unique Threats:** {len(result.threats)} ({len(confirmed)} confirmed, {len(potential)} potential)")
        md.append("---\n")
        
        # ========================================
        # SECTION 1: SYSTEM ARCHITECTURE
        # ========================================
        md.append("## 1. System Architecture")
        
        md.append("\n**Components:**")
        for comp in result.architecture.components:
            md.append(f"- **{comp.name}** ({comp.type})")
            
        md.append("\n**Data Flows:**")
        for flow in result.architecture.flows:
            md.append(f"- {flow.source_id} → {flow.target_id} [{flow.protocol}]")

        if result.mermaid_diagram:
            md.append("\n### Architecture Diagram")
            md.append("```mermaid")
            md.append(result.mermaid_diagram)
            md.append("```\n")

        # ========================================
        # SECTION 2: CONFIRMED RISKS
        # ========================================
        md.append("## 2. Confirmed Risks")
        if not confirmed:
            md.append("*No confirmed risks detected.*\n")
        else:
            md.append(f"The following {len(confirmed)} risks are backed by verified evidence:\n")
            for t in confirmed:
                md.append(ReportGenerator._format_threat(t))

        # ========================================
        # SECTION 3: POTENTIAL RISKS (ASSUMPTION-BASED)
        # ========================================
        md.append("## 3. Potential Risks (Assumption-Based)")
        if not potential:
            md.append("*No potential risks detected.*\n")
        else:
            md.append(f"The following {len(potential)} risks are based on missing or unclear information:\n")
            for t in potential:
                md.append(ReportGenerator._format_threat(t))

        md.append("\n---\n")
        md.append("*Generated by AI Threat Modeler*")
        
        return "\n".join(md)

    @staticmethod
    def _format_threat(t: Threat) -> str:
        """Formats a single threat for markdown output."""
        lines = []
        
        # Header with STRIDE category
        stride_label = f" ({t.stride_category})" if t.stride_category and t.stride_category != t.category else ""
        lines.append(f"### [{t.severity.upper()}] {t.title}{stride_label}")
        lines.append(f"**ID:** {t.id} | **Category:** {t.category} | **Confidence:** {t.confidence}")
        lines.append("")
        lines.append(f"**Why this exists:** {t.description}")
        lines.append("")
        
        # Affected parts
        if t.affected_components:
            lines.append(f"**Affected Components:** {', '.join(t.affected_components)}")
        if t.affected_data_flows:
            lines.append(f"**Affected Data Flows:** {', '.join(t.affected_data_flows)}")
        
        # Evidence
        if t.evidence:
            lines.append("\n**Evidence:**")
            for ev in t.evidence:
                lines.append(f"- {ev}")
        
        # Mitigation
        lines.append(f"\n**Mitigation:** {t.mitigation}")
        lines.append("")
        
        return "\n".join(lines)
